"""
Django settings for compliance_backend project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vt(-o@*8*nug$coi_gw-v649xjezi4zely)kx9li=!dyql4uds'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',  # ← JWT authentication library
    'corsheaders',               # ← CORS support for React frontend
    'api_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'compliance_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'compliance_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ==========================================
# CORS Configuration (for React frontend)
# ==========================================
# Explicitly allow the React dev servers (CRA port 3000, Vite port 5173)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Allow cookies/auth headers to be sent cross-origin (needed for session auth later)
CORS_ALLOW_CREDENTIALS = True


# ==========================================
# Django REST Framework Global Configuration
# ==========================================
# These settings apply to EVERY view unless a view explicitly overrides them.
# IsAuthenticated: rejects any request that does not carry a valid JWT → HTTP 401.
# JWTAuthentication: tells DRF to look for a "Authorization: Bearer <token>" header.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# ==========================================
# Simple JWT Token Configuration
# ==========================================
# Docs: https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
from datetime import timedelta

SIMPLE_JWT = {
    # Access token: short-lived credential sent with every API request.
    # 60 minutes is a practical balance between security and usability for a demo.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # Refresh token: long-lived token used ONLY to obtain new access tokens.
    # The user stays logged in for 7 days without re-entering credentials.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # When True, a new refresh token is issued each time you call /api/token/refresh/.
    # This is a "rotating token" pattern — old refresh tokens are immediately invalidated,
    # which prevents stolen tokens from being reused indefinitely.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # requires 'rest_framework_simplejwt.token_blacklist' in INSTALLED_APPS (optional)

    # The HTTP header and prefix the library looks for.
    # Final header sent by React: Authorization: Bearer <access_token>
    'AUTH_HEADER_TYPES': ('Bearer',),

    # The claim inside the JWT payload used to identify the user.
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Algorithm used to sign the token. HS256 is the industry default for symmetric signing.
    'ALGORITHM': 'HS256',

    # simplejwt signs the JWT with Django's SECRET_KEY — keep that key secret in production!
    'SIGNING_KEY': SECRET_KEY,
}

