# Generated by Django 6.0.8 on 2026-08-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique identifier for the animal', max_length=50, unique=True)),
                ('species', models.CharField(help_text='e.g., Cattle, Sheep, Pig', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_kg', models.FloatField()),
                ('age_months', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage_mg_kg', models.FloatField()),
                ('route', models.CharField(help_text='e.g., Injectable, Oral, Topical', max_length=50)),
                ('health_status', models.CharField(help_text='e.g., Healthy, Mild Infection, Severe Infection', max_length=50)),
                ('predicted_clearance_days', models.FloatField(blank=True, null=True)),
                ('safe_market_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api_app.livestock')),
            ],
        ),
    ]
