# Generated by Django 6.0.8 on 2026-08-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentprescription',
            name='final_safe_market_date',
            field=models.DateField(blank=True, help_text="Vet's overriding market date. Only populated when vet_decision_status='Modified'. Farmers should always follow this date over the AI's safe_market_date.", null=True),
        ),
        migrations.AddField(
            model_name='treatmentprescription',
            name='vet_clinical_notes',
            field=models.TextField(blank=True, help_text="Vet's clinical observations, reasoning, or instructions for the farmer.", null=True),
        ),
        migrations.AddField(
            model_name='treatmentprescription',
            name='vet_decision_status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Modified', 'Date Modified'), ('Rejected', 'Treatment Rejected')], default='Pending', help_text="The veterinarian's formal review decision on this AI-generated prescription.", max_length=20),
        ),
    ]
